name: My First GitHub Actions  # Workflow name

# When this workflow should run
on: [push]  # triggers on any push

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Pulls your repo code into the GitHub runner
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: node -v #tree #Shows the folder structure of your repo (debugging)
